apiVersion: v1
kind: ConfigMap
metadata:
  name: app-config
  namespace: devopssrepractice
  labels:
    app.kubernetes.io/part-of: devopssrepractice
data:
  NODE_ENV: production
  API_PORT: "5000"
  WEB_PORT: "3000"
  FRONTEND_URL: "https://devopssrepractice.com"
  NEXT_PUBLIC_API_URL: "https://api.devopssrepractice.com"
  PG_DATABASE: devopssrepractice
  PG_PORT: "5432"
